name: "httpshow"

services:
  httpshow:
    image: quay.io/miniboat/httpshow:0.3.1
    container_name: httpshow
    ports:
      - 8000:8000
    environment:
      - "TZ=Europe/Zurich"
      - "HTTPSHOW_CONFIG_FILE="
    env_file: ".env"
    restart: unless-stopped
