name: "httpshow"

services:
  httpshow:
    image: harbor.svc.marmira.com/services/httpshow:0.4.2
    container_name: httpshow
    ports:
      - 8001:8000
    environment:
      - "TZ=Europe/Zurich"
      - "HTTPSHOW_LOG_LEVEL=info"
      - "HTTPSHOW_CONFIG_FILE="
    env_file: "test.env"
    restart: unless-stopped
