{{- if eq .Values.ingress.type "httpproxy" -}}
{{-   $fullName := include "httpshow.fullname" . -}}
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: {{ $fullName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "httpshow.labels" $ | nindent 4 }}
  annotations:
    {{- include "httpshow.annotations" $ | nindent 4 }}
    {{- with $.Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  virtualhost:
    fqdn: {{ $.Values.ingress.dns.hostname }}
    {{- if ne $.Values.ingress.tls.secretName "" }}
    tls:
      secretName: {{ $.Values.ingress.tls.secretName }}
    {{- end }}
  routes:
    - conditions:
      - prefix: "/"
      {{- if eq $.Values.ingress.tls.secretName "" }}
      permitInsecure: true
      {{- end }}
      services:
        - name: {{ $fullName }}
          port: {{ .Values.service.port }}
      {{- if ne $.Values.ingress.timeout "" }}
      timeoutPolicy:
        response: {{ $.Values.ingress.timeout }}
      {{- end }}
{{- end -}}
