apiVersion: v1
kind: Secret
metadata:
  name: {{ include "httpshow.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "httpshow.labels" $ | nindent 4 }}
  annotations:
    {{- include "httpshow.annotations" $ | nindent 4 }}
type: Opaque
stringData:
  app-secret: {{ randAlphaNum 32 | b64enc | quote }}
  oidc-client-id: {{ .Values.config.oidc.client.id }}
  oidc-client-secret: {{ .Values.config.oidc.client.secret }}
  token-exchange-client-id: {{ .Values.config.tokenExchange.client.id }}
  token-exchange-client-secret: {{ .Values.config.tokenExchange.client.secret }}
