apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "httpshow.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "httpshow.labels" $ | nindent 4 }}
  annotations:
    {{- include "httpshow.annotations" $ | nindent 4 }}
